version: '3.7'

services:
  app:
    image: php:7.4-cli
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    user: "1000:1000"

  composer_installation:
    image: composer
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs
    user: "1000:1000"
